#!/bin/bash
# It's just me trying to automate my git commits because why not

# git config --global user.name "magonazz1"
# git config --global user.email "martinmagonazz@outlook.com"
git add .
git commit -m "uplink - tasks"
git push
